// RemoteCompanionCN - auto-generated by gen.py, do not edit by hand
#import <UIKit/UIKit.h>

static NSDictionary *RCCNExact;
static NSArray *RCCNRegex;   // NSArray of (NSRegularExpression*, NSArray<NSString*>* templates)

static NSDictionary *RCCNLower;

static NSString *RCCNTranslate(NSString *src) {
    if (!src || src.length == 0 || src.length > 400) return src;
    NSString *hit = RCCNExact[src];
    if (hit) return hit;
    hit = RCCNLower[[src lowercaseString]];
    if (hit) return hit;
    for (NSArray *pair in RCCNRegex) {
        NSRegularExpression *re = pair[0];
        NSArray *templates = pair[1];
        NSTextCheckingResult *m = [re firstMatchInString:src options:0 range:NSMakeRange(0, src.length)];
        if (!m) continue;
        for (NSString *tpl in templates) {
            NSString *out = tpl;
            for (NSUInteger i = 0; i < m.numberOfRanges - 1 && i < 3; i++) {
                NSString *val = [src substringWithRange:[m rangeAtIndex:i + 1]];
                out = [out stringByReplacingOccurrencesOfString:[NSString stringWithFormat:@"{%lu}", (unsigned long)i] withString:val];
            }
            return out;
        }
    }
    return src;
}

static void RCCNInit(void) {
    RCCNExact = [@{
        @"ACTION SEQUENCE" : @"\u52a8\u4f5c\u5e8f\u5217",
        @"Access Token" : @"\u8bbf\u95ee\u4ee4\u724c",
        @"Action Options" : @"\u52a8\u4f5c\u9009\u9879",
        @"Actions" : @"\u52a8\u4f5c",
        @"Add Delay" : @"\u6dfb\u52a0\u5ef6\u8fdf",
        @"Add Else If" : @"\u6dfb\u52a0\u5426\u5219\u5982\u679c",
        @"Add Else" : @"\u6dfb\u52a0\u5426\u5219",
        @"Add Nested If" : @"\u6dfb\u52a0\u5d4c\u5957\u5982\u679c",
        @"Add" : @"\u6dfb\u52a0",
        @"App Launch" : @"\u5e94\u7528\u542f\u52a8",
        @"App" : @"\u5e94\u7528",
        @"Are you sure you want to clear all actions from this trigger?" : @"\u786e\u5b9a\u8981\u6e05\u9664\u6b64\u89e6\u53d1\u5668\u7684\u5168\u90e8\u52a8\u4f5c\u5417\uff1f",
        @"Bluetooth Device" : @"\u84dd\u7259\u8bbe\u5907",
        @"Broker Host" : @"\u670d\u52a1\u5668\u4e3b\u673a",
        @"Cancel" : @"\u53d6\u6d88",
        @"Change Macro\u2026" : @"\u66f4\u6539\u5b8f\u2026",
        @"Choose a status to evaluate" : @"\u9009\u62e9\u8981\u5224\u65ad\u7684\u72b6\u6001",
        @"Clear All Actions" : @"\u6e05\u9664\u5168\u90e8\u52a8\u4f5c",
        @"Clear" : @"\u6e05\u9664",
        @"Client ID" : @"\u5ba2\u6237\u7aef ID",
        @"Configuration file has been saved." : @"\u914d\u7f6e\u6587\u4ef6\u5df2\u4fdd\u5b58\u3002",
        @"Configuration restored. Return to Triggers to see changes." : @"\u914d\u7f6e\u5df2\u6062\u590d\u3002\u8fd4\u56de\u89e6\u53d1\u5668\u9875\u67e5\u770b\u66f4\u6539\u3002",
        @"Connected to Device" : @"\u5df2\u8fde\u63a5\u8bbe\u5907",
        @"Connected to Home Assistant successfully!" : @"\u5df2\u6210\u529f\u8fde\u63a5 Home Assistant\uff01",
        @"Connected to Keyboard Maestro Web Server successfully!" : @"\u5df2\u6210\u529f\u8fde\u63a5 Keyboard Maestro Web \u670d\u52a1\u5668\uff01",
        @"Connected to Network" : @"\u5df2\u8fde\u63a5\u7f51\u7edc",
        @"Connecting to Home Assistant..." : @"\u6b63\u5728\u8fde\u63a5 Home Assistant\u2026",
        @"Connecting to Keyboard Maestro Web Server..." : @"\u6b63\u5728\u8fde\u63a5 Keyboard Maestro Web \u670d\u52a1\u5668\u2026",
        @"Connecting to MQTT Broker..." : @"\u6b63\u5728\u8fde\u63a5 MQTT \u670d\u52a1\u5668\u2026",
        @"Connection Failed" : @"\u8fde\u63a5\u5931\u8d25",
        @"Connection Successful" : @"\u8fde\u63a5\u6210\u529f",
        @"Copied to Clipboard" : @"\u5df2\u590d\u5236\u5230\u526a\u8d34\u677f",
        @"Copied!" : @"\u5df2\u590d\u5236\uff01",
        @"Copy Path" : @"\u590d\u5236\u8def\u5f84",
        @"Copy Settings" : @"\u590d\u5236\u8bbe\u7f6e",
        @"Copy" : @"\u590d\u5236",
        @"Could not connect to MQTT broker" : @"\u65e0\u6cd5\u8fde\u63a5 MQTT \u670d\u52a1\u5668",
        @"Could not export configuration" : @"\u65e0\u6cd5\u5bfc\u51fa\u914d\u7f6e",
        @"Custom Swipe" : @"\u81ea\u5b9a\u4e49\u6ed1\u52a8",
        @"Day Required" : @"\u5fc5\u987b\u9009\u62e9\u65e5\u671f",
        @"Debug Log" : @"\u8c03\u8bd5\u65e5\u5fd7",
        @"Default Topic Prefix" : @"\u9ed8\u8ba4\u4e3b\u9898\u524d\u7f00",
        @"Delete Block" : @"\u5220\u9664\u4ee3\u7801\u5757",
        @"Delete Else If" : @"\u5220\u9664\u5426\u5219\u5982\u679c",
        @"Delete" : @"\u5220\u9664",
        @"Device Locked" : @"\u8bbe\u5907\u5df2\u9501\u5b9a",
        @"Device Unlocked" : @"\u8bbe\u5907\u5df2\u89e3\u9501",
        @"Disabled" : @"\u5df2\u505c\u7528",
        @"Disconnected from Device" : @"\u5df2\u65ad\u5f00\u8bbe\u5907",
        @"Disconnected from Network" : @"\u5df2\u65ad\u5f00\u7f51\u7edc",
        @"Edit Action" : @"\u7f16\u8f91\u52a8\u4f5c",
        @"Edit Condition" : @"\u7f16\u8f91\u6761\u4ef6",
        @"Edit Delay" : @"\u7f16\u8f91\u5ef6\u8fdf",
        @"Edit Parameter / Value\u2026" : @"\u7f16\u8f91\u53c2\u6570/\u503c\u2026",
        @"Enable All Triggers" : @"\u542f\u7528\u5168\u90e8\u89e6\u53d1\u5668",
        @"Enable Home Assistant" : @"\u542f\u7528 Home Assistant",
        @"Enable Keyboard Maestro" : @"\u542f\u7528 Keyboard Maestro",
        @"Enable MQTT" : @"\u542f\u7528 MQTT",
        @"Enabled (Default URL)" : @"\u5df2\u542f\u7528\uff08\u9ed8\u8ba4 URL\uff09",
        @"Enabled (URL not configured)" : @"\u5df2\u542f\u7528\uff08URL \u672a\u914d\u7f6e\uff09",
        @"End Time (e.g. 17:00)" : @"\u7ed3\u675f\u65f6\u95f4\uff08\u5982 17:00\uff09",
        @"Ensure AirPlay devices are reachable." : @"\u8bf7\u786e\u4fdd AirPlay \u8bbe\u5907\u53ef\u8fbe\u3002",
        @"Ensure Bluetooth devices are paired." : @"\u8bf7\u786e\u4fdd\u84dd\u7259\u8bbe\u5907\u5df2\u914d\u5bf9\u3002",
        @"Enter Home Assistant command or entity ID (e.g. toggle light.bedroom or call light.turn_on light.bedroom):" : @"\u8f93\u5165 Home Assistant \u547d\u4ee4\u6216\u5b9e\u4f53 ID\uff08\u5982 toggle light.bedroom \u6216 call light.turn_on light.bedroom\uff09\uff1a",
        @"Enter IP address or hostname of your MQTT broker:" : @"\u8f93\u5165 MQTT \u670d\u52a1\u5668 IP \u6216\u4e3b\u673a\u540d\uff1a",
        @"Enter Macro Name or UUID (and optional trigger value):" : @"\u8f93\u5165\u5b8f\u540d\u79f0\u6216 UUID\uff08\u53ef\u9644\u5e26\u89e6\u53d1\u503c\uff09\uff1a",
        @"Enter SSID" : @"\u8f93\u5165 SSID",
        @"Enter a new name for this NFC tag:" : @"\u8f93\u5165\u6b64 NFC \u6807\u7b7e\u7684\u65b0\u540d\u79f0\uff1a",
        @"Enter a value (0-100)" : @"\u8f93\u5165\u6570\u503c\uff080-100\uff09",
        @"Enter default topic prefix for published events:" : @"\u8f93\u5165\u4e8b\u4ef6\u53d1\u5e03\u7684\u9ed8\u8ba4\u4e3b\u9898\u524d\u7f00\uff1a",
        @"Enter delay in seconds" : @"\u8f93\u5165\u5ef6\u8fdf\u79d2\u6570",
        @"Enter exact device name" : @"\u8f93\u5165\u786e\u5207\u8bbe\u5907\u540d",
        @"Enter optional broker password:" : @"\u8f93\u5165\u670d\u52a1\u5668\u5bc6\u7801\uff08\u53ef\u9009\uff09\uff1a",
        @"Enter optional broker username:" : @"\u8f93\u5165\u670d\u52a1\u5668\u7528\u6237\u540d\uff08\u53ef\u9009\uff09\uff1a",
        @"Enter optional trigger parameter/value passed to KM %TriggerValue%:" : @"\u8f93\u5165\u4f20\u7ed9 KM %TriggerValue% \u7684\u89e6\u53d1\u53c2\u6570/\u503c\uff08\u53ef\u9009\uff09\uff1a",
        @"Enter start and end time (e.g. 09:00 - 17:00 or 9:00 AM - 5:00 PM):" : @"\u8f93\u5165\u5f00\u59cb\u4e0e\u7ed3\u675f\u65f6\u95f4\uff08\u5982 09:00 - 17:00\uff09\uff1a",
        @"Enter terminal command (runs as root)" : @"\u8f93\u5165\u7ec8\u7aef\u547d\u4ee4\uff08\u4ee5 root \u8fd0\u884c\uff09",
        @"Enter the MQTT topic and payload to publish:" : @"\u8f93\u5165\u8981\u53d1\u5e03\u7684 MQTT \u4e3b\u9898\u4e0e\u5185\u5bb9\uff1a",
        @"Enter the Web Server URL from Keyboard Maestro Preferences (e.g. http://192.168.1.50:4490 or https://192.168.1.30:4491):" : @"\u8f93\u5165 Keyboard Maestro \u504f\u597d\u8bbe\u7f6e\u4e2d\u7684 Web \u670d\u52a1\u5668 URL\uff08\u5982 http://192.168.1.50:4490\uff09\uff1a",
        @"Enter the full base URL of your Home Assistant instance:" : @"\u8f93\u5165 Home Assistant \u7684\u5b8c\u6574\u57fa\u7840 URL\uff1a",
        @"Enter the optional password configured in Keyboard Maestro Web Server preferences:" : @"\u8f93\u5165 Keyboard Maestro Web \u670d\u52a1\u5668\u504f\u597d\u4e2d\u8bbe\u7f6e\u7684\u5bc6\u7801\uff08\u53ef\u9009\uff09\uff1a",
        @"Enter the optional username configured in Keyboard Maestro Web Server preferences:" : @"\u8f93\u5165 Keyboard Maestro Web \u670d\u52a1\u5668\u504f\u597d\u4e2d\u8bbe\u7f6e\u7684\u7528\u6237\u540d\uff08\u53ef\u9009\uff09\uff1a",
        @"Enter the port number of your MQTT broker (default: 1883):" : @"\u8f93\u5165 MQTT \u670d\u52a1\u5668\u7aef\u53e3\uff08\u9ed8\u8ba4 1883\uff09\uff1a",
        @"Enter toast title, subtitle and SFSymbol name" : @"\u8f93\u5165\u5f39\u7a97\u6807\u9898\u3001\u526f\u6807\u9898\u548c SFSymbol \u540d\u79f0",
        @"Enter unique client identifier for this device:" : @"\u8f93\u5165\u672c\u8bbe\u5907\u552f\u4e00\u7684\u5ba2\u6237\u7aef\u6807\u8bc6\uff1a",
        @"Enter value passed to KM %TriggerValue% (leave empty for none):" : @"\u8f93\u5165\u4f20\u7ed9 KM %TriggerValue% \u7684\u503c\uff08\u7559\u7a7a\u4e3a\u65e0\uff09\uff1a",
        @"Error" : @"\u9519\u8bef",
        @"Execute as Root" : @"\u4ee5 Root \u6267\u884c",
        @"Export Configuration" : @"\u5bfc\u51fa\u914d\u7f6e",
        @"Export Error" : @"\u5bfc\u51fa\u9519\u8bef",
        @"Export Failed" : @"\u5bfc\u51fa\u5931\u8d25",
        @"Export Successful" : @"\u5bfc\u51fa\u6210\u529f",
        @"Failed to Load Entities" : @"\u52a0\u8f7d\u5b9e\u4f53\u5931\u8d25",
        @"Failed to Load Macros" : @"\u52a0\u8f7d\u5b8f\u5931\u8d25",
        @"Failed to fetch devices" : @"\u83b7\u53d6\u8bbe\u5907\u5931\u8d25",
        @"Favorite" : @"\u6536\u85cf",
        @"Fetching paired devices..." : @"\u6b63\u5728\u83b7\u53d6\u5df2\u914d\u5bf9\u8bbe\u5907\u2026",
        @"HTTP 401: Unauthorized (Check Username / Password)" : @"HTTP 401\uff1a\u672a\u6388\u6743\uff08\u68c0\u67e5\u7528\u6237\u540d/\u5bc6\u7801\uff09",
        @"Home Assistant Command" : @"Home Assistant \u547d\u4ee4",
        @"Home Assistant Not Configured" : @"Home Assistant \u672a\u914d\u7f6e",
        @"Home Assistant URL" : @"Home Assistant URL",
        @"Home Assistant" : @"Home Assistant",
        @"Import Actions" : @"\u5bfc\u5165\u52a8\u4f5c",
        @"Import Configuration" : @"\u5bfc\u5165\u914d\u7f6e",
        @"Import Failed" : @"\u5bfc\u5165\u5931\u8d25",
        @"Import Successful" : @"\u5bfc\u5165\u6210\u529f",
        @"Import" : @"\u5bfc\u5165",
        @"Integrations" : @"\u96c6\u6210\u670d\u52a1",
        @"Invalid configuration file" : @"\u914d\u7f6e\u6587\u4ef6\u65e0\u6548",
        @"Keyboard Maestro Macro" : @"Keyboard Maestro \u5b8f",
        @"Keyboard Maestro Not Configured" : @"Keyboard Maestro \u672a\u914d\u7f6e",
        @"Keyboard Maestro Password" : @"Keyboard Maestro \u5bc6\u7801",
        @"Keyboard Maestro Server URL" : @"Keyboard Maestro \u670d\u52a1\u5668 URL",
        @"Keyboard Maestro Username" : @"Keyboard Maestro \u7528\u6237\u540d",
        @"Keyboard Maestro" : @"Keyboard Maestro",
        @"Keyword to match" : @"\u8981\u5339\u914d\u7684\u5173\u952e\u8bcd",
        @"Leave empty for any payload, or e.g. ON" : @"\u7559\u7a7a\u5339\u914d\u4efb\u610f\u5185\u5bb9\uff0c\u6216\u5982 ON",
        @"Loading..." : @"\u52a0\u8f7d\u4e2d\u2026",
        @"Long-Lived Access Token" : @"\u957f\u671f\u8bbf\u95ee\u4ee4\u724c",
        @"MQTT Broker Host" : @"MQTT \u670d\u52a1\u5668\u4e3b\u673a",
        @"MQTT Client ID" : @"MQTT \u5ba2\u6237\u7aef ID",
        @"MQTT Password" : @"MQTT \u5bc6\u7801",
        @"MQTT Port" : @"MQTT \u7aef\u53e3",
        @"MQTT Topic" : @"MQTT \u4e3b\u9898",
        @"MQTT Username" : @"MQTT \u7528\u6237\u540d",
        @"MQTT" : @"MQTT",
        @"MQTT: Publish Topic" : @"MQTT\uff1a\u53d1\u5e03\u4e3b\u9898",
        @"Macro Name or UUID (e.g. Sleep Display)" : @"\u5b8f\u540d\u79f0\u6216 UUID\uff08\u5982 Sleep Display\uff09",
        @"Macro" : @"\u5b8f",
        @"Manual Entry" : @"\u624b\u52a8\u8f93\u5165",
        @"Media Paused" : @"\u5a92\u4f53\u5df2\u6682\u505c",
        @"Media Playing" : @"\u5a92\u4f53\u64ad\u653e\u4e2d",
        @"Media Track Changed" : @"\u5a92\u4f53\u66f2\u76ee\u5207\u6362",
        @"Missing Configuration" : @"\u7f3a\u5c11\u914d\u7f6e",
        @"Missing Topic" : @"\u7f3a\u5c11\u4e3b\u9898",
        @"Modify the command" : @"\u4fee\u6539\u547d\u4ee4",
        @"My Device" : @"\u6211\u7684\u8bbe\u5907",
        @"My Tag" : @"\u6211\u7684\u6807\u7b7e",
        @"NFC Error" : @"NFC \u9519\u8bef",
        @"NFC Not Supported" : @"\u4e0d\u652f\u6301 NFC",
        @"NFC Scanning" : @"NFC \u626b\u63cf\u4e2d",
        @"NFC Tag" : @"NFC \u6807\u7b7e",
        @"Name Required" : @"\u5fc5\u987b\u586b\u5199\u540d\u79f0",
        @"New Trigger" : @"\u65b0\u5efa\u89e6\u53d1\u5668",
        @"No Actions" : @"\u65e0\u52a8\u4f5c",
        @"No Devices Found" : @"\u672a\u627e\u5230\u8bbe\u5907",
        @"No Paired Devices Found" : @"\u672a\u627e\u5230\u5df2\u914d\u5bf9\u8bbe\u5907",
        @"No actions configured for this trigger. Tap to add actions first." : @"\u6b64\u89e6\u53d1\u5668\u5c1a\u672a\u914d\u7f6e\u52a8\u4f5c\uff0c\u8bf7\u5148\u70b9\u6309\u6dfb\u52a0\u52a8\u4f5c\u3002",
        @"No parameter configured" : @"\u672a\u914d\u7f6e\u53c2\u6570",
        @"No valid actions found." : @"\u672a\u627e\u5230\u6709\u6548\u52a8\u4f5c\u3002",
        @"Not Configured" : @"\u672a\u914d\u7f6e",
        @"Not configured" : @"\u672a\u914d\u7f6e",
        @"Notification" : @"\u901a\u77e5",
        @"OK" : @"\u597d",
        @"Optional" : @"\u53ef\u9009",
        @"Parameter / Value (optional)" : @"\u53c2\u6570/\u503c\uff08\u53ef\u9009\uff09",
        @"Password" : @"\u5bc6\u7801",
        @"Paste Above" : @"\u7c98\u8d34\u5230\u4e0a\u65b9",
        @"Paste Below" : @"\u7c98\u8d34\u5230\u4e0b\u65b9",
        @"Paste the access token generated from your Home Assistant profile:" : @"\u7c98\u8d34 Home Assistant \u4e2a\u4eba\u8d44\u6599\u9875\u751f\u6210\u7684\u8bbf\u95ee\u4ee4\u724c\uff1a",
        @"Paste" : @"\u7c98\u8d34",
        @"Payload (e.g. ON, TOGGLE, 1, or JSON)" : @"\u5185\u5bb9\uff08\u5982 ON\u3001TOGGLE\u30011 \u6216 JSON\uff09",
        @"Please configure Broker Host first." : @"\u8bf7\u5148\u914d\u7f6e\u670d\u52a1\u5668\u4e3b\u673a\u3002",
        @"Please configure Keyboard Maestro Web Server URL first." : @"\u8bf7\u5148\u914d\u7f6e Keyboard Maestro Web \u670d\u52a1\u5668 URL\u3002",
        @"Please configure Server URL and Access Token first." : @"\u8bf7\u5148\u914d\u7f6e\u670d\u52a1\u5668 URL \u548c\u8bbf\u95ee\u4ee4\u724c\u3002",
        @"Please configure your Home Assistant Server URL and Access Token in Settings." : @"\u8bf7\u5728\u8bbe\u7f6e\u4e2d\u914d\u7f6e Home Assistant \u670d\u52a1\u5668 URL \u548c\u8bbf\u95ee\u4ee4\u724c\u3002",
        @"Please configure your Keyboard Maestro Web Server URL in Settings." : @"\u8bf7\u5728\u8bbe\u7f6e\u4e2d\u914d\u7f6e Keyboard Maestro Web \u670d\u52a1\u5668 URL\u3002",
        @"Please enter a WiFi network name." : @"\u8bf7\u8f93\u5165 WiFi \u7f51\u7edc\u540d\u79f0\u3002",
        @"Please enter an MQTT topic to subscribe to." : @"\u8bf7\u8f93\u5165\u8981\u8ba2\u9605\u7684 MQTT \u4e3b\u9898\u3002",
        @"Please install SpringCuts from Havoc to enable shortcuts support." : @"\u8bf7\u4ece Havoc \u6e90\u5b89\u88c5 SpringCuts \u4ee5\u542f\u7528\u5feb\u6377\u6307\u4ee4\u652f\u6301\u3002",
        @"Please select at least one day." : @"\u8bf7\u81f3\u5c11\u9009\u62e9\u4e00\u5929\u3002",
        @"Please wait" : @"\u8bf7\u7a0d\u5019",
        @"Port" : @"\u7aef\u53e3",
        @"Power Connected" : @"\u5df2\u63a5\u901a\u7535\u6e90",
        @"Power Disconnected" : @"\u7535\u6e90\u5df2\u65ad\u5f00",
        @"Ready to Scan (NDEF Mode)..." : @"\u51c6\u5907\u626b\u63cf\uff08NDEF \u6a21\u5f0f\uff09\u2026",
        @"Ready to Scan (Tag Mode)..." : @"\u51c6\u5907\u626b\u63cf\uff08\u6807\u7b7e\u6a21\u5f0f\uff09\u2026",
        @"Ready to Scan" : @"\u51c6\u5907\u626b\u63cf",
        @"Record Tap" : @"\u5f55\u5236\u70b9\u51fb",
        @"Remove Else" : @"\u79fb\u9664\u5426\u5219",
        @"Remove Parameter" : @"\u79fb\u9664\u53c2\u6570",
        @"Rename Tag" : @"\u91cd\u547d\u540d\u6807\u7b7e",
        @"Retry" : @"\u91cd\u8bd5",
        @"Root Command" : @"Root \u547d\u4ee4",
        @"SFSymbol name (optional, e.g. info.circle)" : @"SFSymbol \u540d\u79f0\uff08\u53ef\u9009\uff0c\u5982 info.circle\uff09",
        @"Save" : @"\u4fdd\u5b58",
        @"Scan Cancelled" : @"\u626b\u63cf\u5df2\u53d6\u6d88",
        @"Scan NFC Tag" : @"\u626b\u63cf NFC \u6807\u7b7e",
        @"Scanning for devices..." : @"\u6b63\u5728\u626b\u63cf\u8bbe\u5907\u2026",
        @"Scheduled Trigger" : @"\u5b9a\u65f6\u89e6\u53d1\u5668",
        @"Search Actions" : @"\u641c\u7d22\u52a8\u4f5c",
        @"Search Apps" : @"\u641c\u7d22\u5e94\u7528",
        @"Search Entities" : @"\u641c\u7d22\u5b9e\u4f53",
        @"Search Macros & Groups" : @"\u641c\u7d22\u5b8f\u4e0e\u5206\u7ec4",
        @"Search Shortcuts" : @"\u641c\u7d22\u5feb\u6377\u6307\u4ee4",
        @"Select Action" : @"\u9009\u62e9\u52a8\u4f5c",
        @"Select AirPlay Device" : @"\u9009\u62e9 AirPlay \u8bbe\u5907",
        @"Select App" : @"\u9009\u62e9\u5e94\u7528",
        @"Select Bluetooth Device" : @"\u9009\u62e9\u84dd\u7259\u8bbe\u5907",
        @"Select Shortcut" : @"\u9009\u62e9\u5feb\u6377\u6307\u4ee4",
        @"Select a system event to trigger actions." : @"\u9009\u62e9\u4e00\u4e2a\u7528\u4e8e\u89e6\u53d1\u52a8\u4f5c\u7684\u7cfb\u7edf\u4e8b\u4ef6\u3002",
        @"Select a trigger type to expand your RemoteCompanion setup." : @"\u9009\u62e9\u89e6\u53d1\u5668\u7c7b\u578b\u4ee5\u6269\u5c55\u4f60\u7684 RemoteCompanion \u8bbe\u7f6e\u3002",
        @"Select desired mode/lens" : @"\u9009\u62e9\u6240\u9700\u6a21\u5f0f/\u955c\u5934",
        @"Select desired state" : @"\u9009\u62e9\u6240\u9700\u72b6\u6001",
        @"Server URL" : @"\u670d\u52a1\u5668 URL",
        @"Set" : @"\u8bbe\u5b9a",
        @"Settings" : @"\u8bbe\u7f6e",
        @"SpringCuts Missing" : @"\u7f3a\u5c11 SpringCuts",
        @"Start Time (e.g. 09:00)" : @"\u5f00\u59cb\u65f6\u95f4\uff08\u5982 09:00\uff09",
        @"Subtitle (optional)" : @"\u526f\u6807\u9898\uff08\u53ef\u9009\uff09",
        @"System Event" : @"\u7cfb\u7edf\u4e8b\u4ef6",
        @"Test Connection" : @"\u6d4b\u8bd5\u8fde\u63a5",
        @"Test Macro" : @"\u6d4b\u8bd5\u5b8f",
        @"Testing Connection..." : @"\u6b63\u5728\u6d4b\u8bd5\u8fde\u63a5\u2026",
        @"There are no actions in this sequence to export." : @"\u6b64\u5e8f\u5217\u6ca1\u6709\u53ef\u5bfc\u51fa\u7684\u52a8\u4f5c\u3002",
        @"This device does not support NFC reading." : @"\u6b64\u8bbe\u5907\u4e0d\u652f\u6301 NFC \u8bfb\u53d6\u3002",
        @"Time of Day Condition" : @"\u65f6\u6bb5\u6761\u4ef6",
        @"Title (required)" : @"\u6807\u9898\uff08\u5fc5\u586b\uff09",
        @"Toast" : @"\u5f39\u7a97",
        @"Topic (e.g. home/livingroom/light/set)" : @"\u4e3b\u9898\uff08\u5982 home/livingroom/light/set\uff09",
        @"Topic Prefix" : @"\u4e3b\u9898\u524d\u7f00",
        @"Trigger (No Parameter)" : @"\u89e6\u53d1\uff08\u65e0\u53c2\u6570\uff09",
        @"Trigger Value / Parameter (optional)" : @"\u89e6\u53d1\u503c/\u53c2\u6570\uff08\u53ef\u9009\uff09",
        @"Trigger with Parameter\u2026" : @"\u5e26\u53c2\u6570\u89e6\u53d1\u2026",
        @"UI Tweaker" : @"\u754c\u9762\u8c03\u6574\u5668",
        @"Unfavorite" : @"\u53d6\u6d88\u6536\u85cf",
        @"Update AirPlay Device" : @"\u66f4\u65b0 AirPlay \u8bbe\u5907",
        @"Update delay in seconds" : @"\u66f4\u65b0\u5ef6\u8fdf\u79d2\u6570",
        @"Update" : @"\u66f4\u65b0",
        @"Username" : @"\u7528\u6237\u540d",
        @"Web Server URL" : @"Web \u670d\u52a1\u5668 URL",
        @"Web UI" : @"\u7f51\u9875\u63a7\u5236\u53f0",
        @"WiFi Network" : @"WiFi \u7f51\u7edc",
        @"e.g. Inbound Alert" : @"\u5982 Inbound Alert",
        @"e.g. com.apple.ShazamNotifications" : @"\u5982 com.apple.ShazamNotifications",
        @"e.g. remotecompanion/cmd/ring" : @"\u5982 remotecompanion/cmd/ring",
        @"x y  (e.g. 195 422)" : @"x y\uff08\u5982 195 422\uff09",
        @"x y ms  (e.g. 195 422 800)" : @"x y \u6beb\u79d2\uff08\u5982 195 422 800\uff09",
        @"x1 y1 x2 y2  (e.g. 195 700 195 200)" : @"x1 y1 x2 y2\uff08\u5982 195 700 195 200\uff09",
        @"192.168.1.50 or broker.local" : @"\u5982 192.168.1.50 \u6216 broker.local",
        @"TAP SCREEN NOW\nto record coordinates" : @"\u73b0\u5728\u70b9\u51fb\u5c4f\u5e55\n\u4ee5\u5f55\u5236\u5750\u6807",
        @"Recording tap in 1..." : @"1 \u79d2\u540e\u5f55\u5236\u70b9\u51fb\u2026",
        @"Recording tap in 2..." : @"2 \u79d2\u540e\u5f55\u5236\u70b9\u51fb\u2026",
        @"Recording tap in 3..." : @"3 \u79d2\u540e\u5f55\u5236\u70b9\u51fb\u2026",
        @"last none" : @"\u65e0\u4e0a\u6b21\u8bb0\u5f55",
        @"2x flash" : @"2x \u95ea\u5149\u706f",
        @"A friendly name displayed in the triggers list." : @"\u5728\u89e6\u53d1\u5668\u5217\u8868\u4e2d\u663e\u793a\u7684\u540d\u79f0\u3002",
        @"Activate Siri" : @"\u6fc0\u6d3b Siri",
        @"Add Action" : @"\u6dfb\u52a0\u52a8\u4f5c",
        @"AirPlay Connect" : @"AirPlay \u8fde\u63a5",
        @"AirPlay Device" : @"AirPlay \u8bbe\u5907",
        @"Airplane Mode" : @"\u98de\u884c\u6a21\u5f0f",
        @"Airplane Off" : @"\u98de\u884c\u6a21\u5f0f \u5173",
        @"Airplane On" : @"\u98de\u884c\u6a21\u5f0f \u5f00",
        @"Airplane Toggle" : @"\u98de\u884c\u6a21\u5f0f \u5207\u6362",
        @"Any App" : @"\u4efb\u610f\u5e94\u7528",
        @"Any Notification" : @"\u4efb\u610f\u901a\u77e5",
        @"App Launch Triggers" : @"\u5e94\u7528\u542f\u52a8\u89e6\u53d1\u5668",
        @"App Switcher" : @"\u5e94\u7528\u5207\u6362\u5668",
        @"Appearance Dark" : @"\u5916\u89c2 \u6df1\u8272",
        @"Appearance Light" : @"\u5916\u89c2 \u6d45\u8272",
        @"Appearance Toggle" : @"\u5916\u89c2 \u5207\u6362",
        @"AudioMix Off" : @"\u97f3\u9891\u6df7\u97f3 \u5173",
        @"AudioMix On" : @"\u97f3\u9891\u6df7\u97f3 \u5f00",
        @"AudioMix Status" : @"\u97f3\u9891\u6df7\u97f3 \u72b6\u6001",
        @"AudioMix Toggle" : @"\u97f3\u9891\u6df7\u97f3 \u5207\u6362",
        @"AudioMix: Toggle" : @"\u97f3\u9891\u6df7\u97f3\uff1a\u5207\u6362",
        @"Authentication failed (check Web Server username/password)" : @"\u8eab\u4efd\u9a8c\u8bc1\u5931\u8d25\uff08\u68c0\u67e5 Web \u670d\u52a1\u5668\u7528\u6237\u540d/\u5bc6\u7801\uff09",
        @"Back" : @"\u8fd4\u56de",
        @"Bad username or password" : @"\u7528\u6237\u540d\u6216\u5bc6\u7801\u9519\u8bef",
        @"Block BG" : @"\u52a8\u4f5c\u5757\u80cc\u666f",
        @"Bluetooth Device Triggers" : @"\u84dd\u7259\u8bbe\u5907\u89e6\u53d1\u5668",
        @"Bluetooth Off" : @"\u84dd\u7259 \u5173",
        @"Bluetooth On" : @"\u84dd\u7259 \u5f00",
        @"Bluetooth Toggle" : @"\u84dd\u7259 \u5207\u6362",
        @"Bottom Bar Gestures" : @"\u5e95\u680f\u624b\u52bf",
        @"Bottom Bar Swipe Left" : @"\u5e95\u680f\u5de6\u6ed1",
        @"Bottom Bar Swipe Right" : @"\u5e95\u680f\u53f3\u6ed1",
        @"Bottom Swipe Up (Center)" : @"\u5e95\u90e8\u4e0a\u6ed1\uff08\u4e2d\u90e8\uff09",
        @"Bottom Swipe Up (Left)" : @"\u5e95\u90e8\u4e0a\u6ed1\uff08\u5de6\u4fa7\uff09",
        @"Bottom Swipe Up (Right)" : @"\u5e95\u90e8\u4e0a\u6ed1\uff08\u53f3\u4fa7\uff09",
        @"Broker Details" : @"Broker \u8be6\u60c5",
        @"Camera" : @"\u76f8\u673a",
        @"Camera Record Toggle" : @"\u5f55\u50cf\u5f00/\u5173",
        @"Camera Shutter / Snap" : @"\u76f8\u673a\u5feb\u95e8/\u6293\u62cd",
        @"Cellular Data" : @"\u8702\u7a9d\u6570\u636e",
        @"Cellular Off" : @"\u8702\u7a9d\u6570\u636e \u5173",
        @"Cellular On" : @"\u8702\u7a9d\u6570\u636e \u5f00",
        @"Cellular Toggle" : @"\u8702\u7a9d\u6570\u636e \u5207\u6362",
        @"Choose which app's notifications to listen for, or leave as 'Any App' to match all incoming notifications." : @"\u9009\u62e9\u8981\u76d1\u542c\u54ea\u4e2a\u5e94\u7528\u7684\u901a\u77e5\uff0c\u6216\u7559\u4f5c\u201c\u4efb\u610f\u5e94\u7528\u201d\u4ee5\u5339\u914d\u6240\u6709\u4f20\u5165\u901a\u77e5\u3002",
        @"Conditional Block" : @"\u6761\u4ef6\u5757",
        @"Configure connections to external services and automations." : @"\u914d\u7f6e\u4e0e\u5916\u90e8\u670d\u52a1\u548c\u81ea\u52a8\u5316\u7684\u8fde\u63a5\u3002",
        @"Configure external service integrations to trigger actions and control third-party automations." : @"\u914d\u7f6e\u5916\u90e8\u670d\u52a1\u96c6\u6210\uff0c\u4ee5\u89e6\u53d1\u52a8\u4f5c\u5e76\u63a7\u5236\u7b2c\u4e09\u65b9\u81ea\u52a8\u5316\u3002",
        @"Configure your MQTT broker host, port, and optional credentials. Standard MQTT 3.1.1 protocol is used." : @"\u914d\u7f6e MQTT Broker \u7684\u4e3b\u673a\u3001\u7aef\u53e3\u548c\u53ef\u9009\u51ed\u636e\u3002\u4f7f\u7528\u6807\u51c6 MQTT 3.1.1 \u534f\u8bae\u3002",
        @"Connect AirPlay" : @"\u8fde\u63a5 AirPlay",
        @"Connect AirPlay..." : @"\u8fde\u63a5 AirPlay\u2026",
        @"Connect Bluetooth..." : @"\u8fde\u63a5\u84dd\u7259\u2026",
        @"Connect to Bluetooth" : @"\u8fde\u63a5\u5230\u84dd\u7259",
        @"Connected to" : @"\u5df2\u8fde\u63a5\u5230",
        @"Connection Details" : @"\u8fde\u63a5\u8be6\u60c5",
        @"Connection failed" : @"\u8fde\u63a5\u5931\u8d25",
        @"Control Center" : @"\u63a7\u5236\u4e2d\u5fc3",
        @"Could not connect to RemoteCompanion tweak (UNIX socket)" : @"\u65e0\u6cd5\u8fde\u63a5\u5230 RemoteCompanion \u63d2\u4ef6\uff08UNIX socket\uff09",
        @"Could not read Tag UID" : @"\u65e0\u6cd5\u8bfb\u53d6\u6807\u7b7e UID",
        @"Current UI Color Tweaks:" : @"\u5f53\u524d\u754c\u9762\u989c\u8272\u8c03\u6574\uff1a",
        @"Custom Lua Script" : @"\u81ea\u5b9a\u4e49 Lua \u811a\u672c",
        @"Delete Currently Playing Song" : @"\u5220\u9664\u5f53\u524d\u64ad\u653e\u6b4c\u66f2",
        @"Device Controls" : @"\u8bbe\u5907\u63a7\u5236",
        @"Device Name" : @"\u8bbe\u5907\u540d\u79f0",
        @"Device State" : @"\u8bbe\u5907\u72b6\u6001",
        @"Disable Action" : @"\u505c\u7528\u52a8\u4f5c",
        @"Disconnect AirPlay" : @"\u65ad\u5f00 AirPlay",
        @"Disconnect Airplay" : @"\u65ad\u5f00 AirPlay",
        @"Disconnect Bluetooth" : @"\u65ad\u5f00\u84dd\u7259",
        @"Disconnect Bluetooth..." : @"\u65ad\u5f00\u84dd\u7259\u2026",
        @"Disconnected from" : @"\u5df2\u4ece\u2026\u65ad\u5f00",
        @"Do Not Disturb" : @"\u52ff\u6270\u6a21\u5f0f",
        @"Do Not Disturb Off" : @"\u52ff\u6270\u6a21\u5f0f \u5173",
        @"Do Not Disturb On" : @"\u52ff\u6270\u6a21\u5f0f \u5f00",
        @"Do Not Disturb Toggle" : @"\u52ff\u6270\u6a21\u5f0f \u5207\u6362",
        @"Done" : @"\u5b8c\u6210",
        @"Edge Gestures" : @"\u5c4f\u5e55\u8fb9\u7f18\u624b\u52bf",
        @"Edit" : @"\u7f16\u8f91",
        @"Edit Bluetooth" : @"\u7f16\u8f91\u84dd\u7259",
        @"Edit Brightness" : @"\u7f16\u8f91\u4eae\u5ea6",
        @"Edit Command" : @"\u7f16\u8f91\u547d\u4ee4",
        @"Edit Lua Script" : @"\u7f16\u8f91 Lua \u811a\u672c",
        @"Edit MQTT Trigger" : @"\u7f16\u8f91 MQTT \u89e6\u53d1\u5668",
        @"Edit Notification" : @"\u7f16\u8f91\u901a\u77e5",
        @"Edit Schedule" : @"\u7f16\u8f91\u8ba1\u5212\u4efb\u52a1",
        @"Edit Volume" : @"\u7f16\u8f91\u97f3\u91cf",
        @"Edit WiFi Trigger" : @"\u7f16\u8f91 WiFi \u89e6\u53d1\u5668",
        @"Else If" : @"\u5426\u5219\u5982\u679c",
        @"Else If Condition" : @"\u5426\u5219\u5982\u679c\u6761\u4ef6",
        @"Enable Action" : @"\u542f\u7528\u52a8\u4f5c",
        @"Enable Home Assistant integration to trigger entity toggles, call services, and run scenes from triggers." : @"\u542f\u7528 Home Assistant \u96c6\u6210\uff1a\u4ece\u89e6\u53d1\u5668\u5207\u6362\u5b9e\u4f53\u3001\u8c03\u7528\u670d\u52a1\u3001\u8fd0\u884c\u573a\u666f\u3002",
        @"Enable Keyboard Maestro integration to trigger macros on your Mac over Wi-Fi or LAN." : @"\u542f\u7528 Keyboard Maestro \u96c6\u6210\uff1a\u901a\u8fc7 Wi-Fi \u6216\u5c40\u57df\u7f51\u89e6\u53d1 Mac \u4e0a\u7684\u5b8f\u3002",
        @"Enable MQTT integration to publish topics and trigger smart home or IoT automations directly." : @"\u542f\u7528 MQTT \u96c6\u6210\uff1a\u76f4\u63a5\u53d1\u5e03\u4e3b\u9898\u5e76\u89e6\u53d1\u667a\u80fd\u5bb6\u5c45/IoT \u81ea\u52a8\u5316\u3002",
        @"Enter Lua code to execute" : @"\u8f93\u5165\u8981\u6267\u884c\u7684 Lua \u4ee3\u7801",
        @"Enter terminal command" : @"\u8f93\u5165\u7ec8\u7aef\u547d\u4ee4",
        @"Execution Time" : @"\u6267\u884c\u65f6\u95f4",
        @"Export Actions" : @"\u5bfc\u51fa\u52a8\u4f5c",
        @"Export your configuration to share or backup. Import to restore." : @"\u5bfc\u51fa\u914d\u7f6e\u7528\u4e8e\u5206\u4eab\u6216\u5907\u4efd\uff0c\u5bfc\u5165\u5373\u53ef\u6062\u590d\u3002",
        @"Failed to create UNIX socket" : @"\u521b\u5efa UNIX socket \u5931\u8d25",
        @"Failed to send command" : @"\u547d\u4ee4\u53d1\u9001\u5931\u8d25",
        @"Flashlight Off" : @"\u624b\u7535\u7b52 \u5173",
        @"Flashlight On" : @"\u624b\u7535\u7b52 \u5f00",
        @"Flashlight Toggle" : @"\u624b\u7535\u7b52 \u5207\u6362",
        @"Front Application" : @"\u524d\u53f0\u5e94\u7528",
        @"Front Selfie" : @"\u524d\u7f6e\u81ea\u62cd",
        @"Haptic Feedback" : @"\u89e6\u89c9\u53cd\u9988",
        @"Hold nearest NFC tag to back of iPhone." : @"\u5c06\u6700\u8fd1\u7684 NFC \u6807\u7b7e\u8d34\u8fd1 iPhone \u80cc\u9762\u3002",
        @"Home Assistant: Control Entity..." : @"Home Assistant\uff1a\u63a7\u5236\u5b9e\u4f53\u2026",
        @"Home Button" : @"\u4e3b\u5c4f\u5e55\u6309\u94ae",
        @"Home Button (Double Click)" : @"\u4e3b\u5c4f\u5e55\u6309\u94ae\uff08\u53cc\u51fb\uff09",
        @"Home Button (Quadruple Click)" : @"\u4e3b\u5c4f\u5e55\u6309\u94ae\uff08\u56db\u51fb\uff09",
        @"Home Button (Triple Click)" : @"\u4e3b\u5c4f\u5e55\u6309\u94ae\uff08\u4e09\u51fb\uff09",
        @"Host is empty" : @"\u4e3b\u673a\u4e3a\u7a7a",
        @"If Condition" : @"\u5982\u679c\u6761\u4ef6",
        @"If Condition..." : @"\u5982\u679c\u6761\u4ef6\u2026",
        @"KM Trigger" : @"KM \u89e6\u53d1\u5668",
        @"Keyboard Maestro: Trigger Macro..." : @"Keyboard Maestro\uff1a\u89e6\u53d1\u5b8f\u2026",
        @"Kill App..." : @"\u7ed3\u675f\u5e94\u7528\u2026",
        @"Kill Application" : @"\u7ed3\u675f\u5e94\u7528",
        @"Leave empty to trigger on any message received on this topic, or enter exact text/JSON payload to match." : @"\u7559\u7a7a\u5219\u5728\u6b64\u4e3b\u9898\u6536\u5230\u4efb\u4f55\u6d88\u606f\u65f6\u89e6\u53d1\uff1b\u6216\u8f93\u5165\u7cbe\u786e\u6587\u672c/JSON \u8f7d\u8377\u8fdb\u884c\u5339\u914d\u3002",
        @"Left Edge Swipe Down" : @"\u5de6\u7f18\u4e0b\u6ed1",
        @"Left Edge Swipe Up" : @"\u5de6\u7f18\u4e0a\u6ed1",
        @"Loading via springcuts -l..." : @"\u6b63\u5728\u901a\u8fc7 springcuts -l \u52a0\u8f7d\u2026",
        @"Location Services" : @"\u5b9a\u4f4d\u670d\u52a1",
        @"Location Services Off" : @"\u5b9a\u4f4d\u670d\u52a1 \u5173",
        @"Location Services On" : @"\u5b9a\u4f4d\u670d\u52a1 \u5f00",
        @"Location Services Status" : @"\u5b9a\u4f4d\u670d\u52a1 \u72b6\u6001",
        @"Location Services Toggle" : @"\u5b9a\u4f4d\u670d\u52a1 \u5207\u6362",
        @"Lock Device" : @"\u9501\u5b9a\u8bbe\u5907",
        @"Lock Status" : @"\u9501\u5b9a\u72b6\u6001",
        @"Lock Toggle" : @"\u9501\u5b9a \u5207\u6362",
        @"Low Power Mode" : @"\u4f4e\u7535\u91cf\u6a21\u5f0f",
        @"Low Power Mode Off" : @"\u4f4e\u7535\u91cf\u6a21\u5f0f \u5173",
        @"Low Power Mode On" : @"\u4f4e\u7535\u91cf\u6a21\u5f0f \u5f00",
        @"Low Power Mode Toggle" : @"\u4f4e\u7535\u91cf\u6a21\u5f0f \u5207\u6362",
        @"Lua Script" : @"Lua \u811a\u672c",
        @"MQTT Publish" : @"MQTT \u53d1\u5e03",
        @"MQTT Subscription Triggers" : @"MQTT \u8ba2\u9605\u89e6\u53d1\u5668",
        @"MQTT Topic cannot be empty" : @"MQTT \u4e3b\u9898\u4e0d\u80fd\u4e3a\u7a7a",
        @"MQTT: Publish Topic..." : @"MQTT\uff1a\u53d1\u5e03\u4e3b\u9898\u2026",
        @"Main BG" : @"\u4e3b\u754c\u9762\u80cc\u666f",
        @"Manually specify a custom notification bundle ID if iOS delivers notifications under a different identifier (e.g. com.apple.ShazamNotifications)." : @"\u5982\u679c iOS \u4ee5\u5176\u4ed6\u6807\u8bc6\u7b26\u6295\u9012\u901a\u77e5\uff08\u5982 com.apple.ShazamNotifications\uff09\uff0c\u53ef\u624b\u52a8\u6307\u5b9a\u81ea\u5b9a\u4e49\u901a\u77e5 Bundle ID\u3002",
        @"Matches text in the title, subtitle, or body (case-insensitive)." : @"\u5339\u914d\u6807\u9898\u3001\u526f\u6807\u9898\u6216\u6b63\u6587\u4e2d\u7684\u6587\u672c\uff08\u4e0d\u533a\u5206\u5927\u5c0f\u5199\uff09\u3002",
        @"Media" : @"\u5a92\u4f53",
        @"Motion Gestures" : @"\u52a8\u4f5c\u624b\u52bf",
        @"Music" : @"\u97f3\u4e50",
        @"Mute Off" : @"\u9759\u97f3 \u5173",
        @"Mute On" : @"\u9759\u97f3 \u5f00",
        @"Mute Status" : @"\u9759\u97f3 \u72b6\u6001",
        @"Mute Toggle" : @"\u9759\u97f3 \u5207\u6362",
        @"NFC Tags" : @"NFC \u6807\u7b7e",
        @"Network Name (SSID)" : @"\u7f51\u7edc\u540d\u79f0\uff08SSID\uff09",
        @"New Bluetooth" : @"\u65b0\u5efa\u84dd\u7259",
        @"New MQTT Trigger" : @"\u65b0\u5efa MQTT \u89e6\u53d1\u5668",
        @"New Notification" : @"\u65b0\u5efa\u901a\u77e5",
        @"New Schedule" : @"\u65b0\u5efa\u8ba1\u5212\u4efb\u52a1",
        @"New WiFi Trigger" : @"\u65b0\u5efa WiFi \u89e6\u53d1\u5668",
        @"Next Track" : @"\u4e0b\u4e00\u66f2",
        @"No AirPlay devices found." : @"\u672a\u627e\u5230 AirPlay \u8bbe\u5907\u3002",
        @"No paired Bluetooth devices found" : @"\u672a\u627e\u5230\u5df2\u914d\u5bf9\u7684\u84dd\u7259\u8bbe\u5907",
        @"Noise Cancellation Off" : @"\u964d\u566a \u5173",
        @"Noise Cancellation On" : @"\u964d\u566a \u5f00",
        @"Not authorized" : @"\u672a\u6388\u6743",
        @"Notification Bundle ID Override (Optional)" : @"\u901a\u77e5 Bundle ID \u8986\u76d6\uff08\u53ef\u9009\uff09",
        @"Notification Triggers" : @"\u901a\u77e5\u89e6\u53d1\u5668",
        @"Open App..." : @"\u6253\u5f00\u5e94\u7528\u2026",
        @"Open Camera" : @"\u6253\u5f00\u76f8\u673a",
        @"Open Camera (Cinematic)" : @"\u6253\u5f00\u76f8\u673a\uff08\u7535\u5f71\u6548\u679c\uff09",
        @"Open Camera (Front Selfie)" : @"\u6253\u5f00\u76f8\u673a\uff08\u524d\u7f6e\u81ea\u62cd\uff09",
        @"Open Camera (Pano)" : @"\u6253\u5f00\u76f8\u673a\uff08\u5168\u666f\uff09",
        @"Open Camera (Photo 0.5x)" : @"\u6253\u5f00\u76f8\u673a\uff08\u7167\u7247 0.5x\uff09",
        @"Open Camera (Photo 2x)" : @"\u6253\u5f00\u76f8\u673a\uff08\u7167\u7247 2x\uff09",
        @"Open Camera (Photo)" : @"\u6253\u5f00\u76f8\u673a\uff08\u7167\u7247\uff09",
        @"Open Camera (Portrait 2x)" : @"\u6253\u5f00\u76f8\u673a\uff08\u4eba\u50cf 2x\uff09",
        @"Open Camera (Portrait)" : @"\u6253\u5f00\u76f8\u673a\uff08\u4eba\u50cf\uff09",
        @"Open Camera (Slo-Mo)" : @"\u6253\u5f00\u76f8\u673a\uff08\u6162\u52a8\u4f5c\uff09",
        @"Open Camera (Time-Lapse)" : @"\u6253\u5f00\u76f8\u673a\uff08\u5ef6\u65f6\u6444\u5f71\uff09",
        @"Open Camera..." : @"\u6253\u5f00\u76f8\u673a\u2026",
        @"Open Control Center" : @"\u6253\u5f00\u63a7\u5236\u4e2d\u5fc3",
        @"Open Video Camera" : @"\u6253\u5f00\u89c6\u9891\u76f8\u673a",
        @"Open Video Camera (2x)" : @"\u6253\u5f00\u89c6\u9891\u76f8\u673a\uff082x\uff09",
        @"Open Video Camera (2x, Flash)" : @"\u6253\u5f00\u89c6\u9891\u76f8\u673a\uff082x\uff0c\u95ea\u5149\u706f\uff09",
        @"Open Video Camera..." : @"\u6253\u5f00\u89c6\u9891\u76f8\u673a\u2026",
        @"Pause" : @"\u6682\u505c",
        @"Payload Match (Optional)" : @"\u8f7d\u8377\u5339\u914d\uff08\u53ef\u9009\uff09",
        @"Photo (0.5x)" : @"\u7167\u7247\uff080.5x\uff09",
        @"Photo (1x)" : @"\u7167\u7247\uff081x\uff09",
        @"Photo (2x)" : @"\u7167\u7247\uff082x\uff09",
        @"Play" : @"\u64ad\u653e",
        @"Play/Pause Toggle" : @"\u64ad\u653e/\u6682\u505c \u5207\u6362",
        @"Player Status" : @"\u64ad\u653e\u5668\u72b6\u6001",
        @"Portrait (1x)" : @"\u4eba\u50cf\uff081x\uff09",
        @"Portrait (2x)" : @"\u4eba\u50cf\uff082x\uff09",
        @"Power + Volume Down" : @"\u7535\u6e90\u952e + \u97f3\u91cf\u51cf",
        @"Power + Volume Up" : @"\u7535\u6e90\u952e + \u97f3\u91cf\u52a0",
        @"Power Button" : @"\u7535\u6e90\u952e",
        @"Power Double-Tap" : @"\u7535\u6e90\u952e\u53cc\u51fb",
        @"Power Long Press" : @"\u7535\u6e90\u952e\u957f\u6309",
        @"Power Quadruple Click" : @"\u7535\u6e90\u952e\u56db\u51fb",
        @"Power Triple Click" : @"\u7535\u6e90\u952e\u4e09\u51fb",
        @"Previous App" : @"\u4e0a\u4e00\u4e2a\u5e94\u7528",
        @"Previous Track" : @"\u4e0a\u4e00\u66f2",
        @"Proximity Sensor" : @"\u8ddd\u79bb\u4f20\u611f\u5668",
        @"Queue Artist" : @"\u52a0\u5165\u827a\u672f\u5bb6\u961f\u5217",
        @"Queue Current Album" : @"\u5f53\u524d\u4e13\u8f91\u52a0\u5165\u961f\u5217",
        @"Refresh Icon Cache" : @"\u5237\u65b0\u56fe\u6807\u7f13\u5b58",
        @"Refresh Icon Cache (uicache)" : @"\u5237\u65b0\u56fe\u6807\u7f13\u5b58\uff08uicache\uff09",
        @"Repeat Days" : @"\u91cd\u590d\u65e5\u671f",
        @"Respring Device" : @"\u91cd\u542f SpringBoard",
        @"Right Edge Swipe Down" : @"\u53f3\u7f18\u4e0b\u6ed1",
        @"Right Edge Swipe Up" : @"\u53f3\u7f18\u4e0a\u6ed1",
        @"Ring Vibrate Off" : @"\u54cd\u94c3\u632f\u52a8 \u5173",
        @"Ring Vibrate On" : @"\u54cd\u94c3\u632f\u52a8 \u5f00",
        @"Ring Vibrate Status" : @"\u54cd\u94c3\u632f\u52a8 \u72b6\u6001",
        @"Ring Vibrate Toggle" : @"\u54cd\u94c3\u632f\u52a8 \u5207\u6362",
        @"Ring Vibration" : @"\u54cd\u94c3\u632f\u52a8",
        @"Ringer Muted (Silent Mode On)" : @"\u94c3\u58f0\u5df2\u9759\u97f3\uff08\u9759\u97f3\u6a21\u5f0f\u5f00\uff09",
        @"Ringer Switch" : @"\u54cd\u94c3/\u9759\u97f3\u5f00\u5173",
        @"Ringer Toggled (Any Change)" : @"\u54cd\u94c3\u5f00\u5173\u5df2\u5207\u6362\uff08\u4efb\u610f\u53d8\u5316\uff09",
        @"Ringer Unmuted (Silent Mode Off)" : @"\u94c3\u58f0\u5df2\u53d6\u6d88\u9759\u97f3\uff08\u9759\u97f3\u6a21\u5f0f\u5173\uff09",
        @"Rotate Lock" : @"\u65cb\u8f6c\u9501\u5b9a",
        @"Rotate Toggle" : @"\u65cb\u8f6c \u5207\u6362",
        @"Rotate Unlock" : @"\u65cb\u8f6c\u89e3\u9501",
        @"Rotation Lock" : @"\u7ad6\u6392\u65b9\u5411\u9501\u5b9a",
        @"Safe Mode" : @"\u5b89\u5168\u6a21\u5f0f",
        @"Scheduled Triggers" : @"\u8ba1\u5212\u4efb\u52a1\u89e6\u53d1\u5668",
        @"Screen Gestures" : @"\u5c4f\u5e55\u624b\u52bf",
        @"Screen Recording" : @"\u5c4f\u5e55\u5f55\u5236",
        @"Screen Recording Status" : @"\u5c4f\u5e55\u5f55\u5236\u72b6\u6001",
        @"Screen Recording Toggle" : @"\u5c4f\u5e55\u5f55\u5236 \u5207\u6362",
        @"Search" : @"\u641c\u7d22",
        @"Select Actions BG" : @"\u52a8\u4f5c\u9009\u62e9\u80cc\u666f",
        @"Select Device" : @"\u9009\u62e9\u8bbe\u5907",
        @"Selection Highlight" : @"\u9009\u4e2d\u9ad8\u4eae",
        @"Set Brightness" : @"\u8bbe\u7f6e\u4eae\u5ea6",
        @"Set Brightness..." : @"\u8bbe\u7f6e\u4eae\u5ea6\u2026",
        @"Set Flashlight" : @"\u8bbe\u7f6e\u624b\u7535\u7b52",
        @"Set Volume" : @"\u8bbe\u7f6e\u97f3\u91cf",
        @"Set Volume..." : @"\u8bbe\u7f6e\u97f3\u91cf\u2026",
        @"Settings BG" : @"\u8bbe\u7f6e\u80cc\u666f",
        @"Shake Device" : @"\u6447\u6643\u8bbe\u5907",
        @"Shortcut names:" : @"\u5feb\u6377\u6307\u4ee4\u540d\u79f0\uff1a",
        @"Shortcuts: Run Shortcut..." : @"\u5feb\u6377\u6307\u4ee4\uff1a\u8fd0\u884c\u5feb\u6377\u6307\u4ee4\u2026",
        @"Shuffle All Songs" : @"\u968f\u673a\u64ad\u653e\u5168\u90e8\u6b4c\u66f2",
        @"Silent Vibrate Off" : @"\u9759\u97f3\u632f\u52a8 \u5173",
        @"Silent Vibrate On" : @"\u9759\u97f3\u632f\u52a8 \u5f00",
        @"Silent Vibrate Status" : @"\u9759\u97f3\u632f\u52a8 \u72b6\u6001",
        @"Silent Vibrate Toggle" : @"\u9759\u97f3\u632f\u52a8 \u5207\u6362",
        @"Silent Vibration" : @"\u9759\u97f3\u632f\u52a8",
        @"Siri Shortcut" : @"Siri \u5feb\u6377\u6307\u4ee4",
        @"Snapper: Close All" : @"Snapper\uff1a\u5168\u90e8\u5173\u95ed",
        @"Snapper: Freeze Screen" : @"Snapper\uff1a\u51bb\u7ed3\u5c4f\u5e55",
        @"Snapper: Instant Snap" : @"Snapper\uff1a\u5373\u65f6\u622a\u56fe",
        @"Snapper: Open Area" : @"Snapper\uff1a\u6253\u5f00\u533a\u57df",
        @"SneakyCam Photo" : @"\u9690\u62cd \u7167\u7247",
        @"SneakyCam Video" : @"\u9690\u62cd \u89c6\u9891",
        @"SneakyCam: Take Photo" : @"\u9690\u62cd\uff1a\u62cd\u7167",
        @"SneakyCam: Toggle Video" : @"\u9690\u62cd\uff1a\u5f55\u50cf\u5207\u6362",
        @"Soft Reboot (ldrestart)" : @"\u8f6f\u91cd\u542f\uff08ldrestart\uff09",
        @"Specify your local or remote Home Assistant instance URL and a Long-Lived Access Token created in your HA profile." : @"\u586b\u5199\u672c\u5730\u6216\u8fdc\u7a0b Home Assistant \u5b9e\u4f8b URL\uff0c\u4ee5\u53ca\u5728 HA \u4e2a\u4eba\u8d44\u6599\u4e2d\u521b\u5efa\u7684\u957f\u671f\u8bbf\u95ee\u4ee4\u724c\u3002",
        @"Start Scan" : @"\u5f00\u59cb\u626b\u63cf",
        @"Start Screen Recording" : @"\u5f00\u59cb\u5c4f\u5e55\u5f55\u5236",
        @"Status Bar Center Hold" : @"\u72b6\u6001\u680f\u4e2d\u90e8\u957f\u6309",
        @"Status Bar Double Tap" : @"\u72b6\u6001\u680f\u53cc\u51fb",
        @"Status Bar Left Hold" : @"\u72b6\u6001\u680f\u5de6\u4fa7\u957f\u6309",
        @"Status Bar Right Hold" : @"\u72b6\u6001\u680f\u53f3\u4fa7\u957f\u6309",
        @"Status Bar Swipe Left" : @"\u72b6\u6001\u680f\u5de6\u6ed1",
        @"Status Bar Swipe Right" : @"\u72b6\u6001\u680f\u53f3\u6ed1",
        @"Stop Screen Recording" : @"\u505c\u6b62\u5c4f\u5e55\u5f55\u5236",
        @"Swipe Down" : @"\u4e0b\u6ed1",
        @"Swipe Left" : @"\u5de6\u6ed1",
        @"Swipe Right" : @"\u53f3\u6ed1",
        @"Swipe Up" : @"\u4e0a\u6ed1",
        @"System" : @"\u7cfb\u7edf",
        @"Tag does not support UID reading" : @"\u6807\u7b7e\u4e0d\u652f\u6301\u8bfb\u53d6 UID",
        @"Tap + to add actions. They will run in sequence when the trigger fires." : @"\u70b9\u6309 + \u6dfb\u52a0\u52a8\u4f5c\u3002\u89e6\u53d1\u5668\u89e6\u53d1\u65f6\u5c06\u6309\u987a\u5e8f\u8fd0\u884c\u3002",
        @"Target App" : @"\u76ee\u6807\u5e94\u7528",
        @"Terminal Command" : @"\u7ec8\u7aef\u547d\u4ee4",
        @"Text Match (Optional)" : @"\u6587\u672c\u5339\u914d\uff08\u53ef\u9009\uff09",
        @"Time Range" : @"\u65f6\u95f4\u8303\u56f4",
        @"Time of Day" : @"\u4e00\u5929\u4e2d\u7684\u65f6\u95f4",
        @"Time of Day (Between)" : @"\u65f6\u95f4\u6bb5\uff08\u4ecb\u4e8e\uff09",
        @"Touch ID Hold (Rest Finger)" : @"Touch ID \u957f\u6309\uff08\u653e\u7f6e\u624b\u6307\uff09",
        @"Touch ID Single Tap" : @"Touch ID \u5355\u51fb",
        @"Transparency Mode" : @"\u901a\u900f\u6a21\u5f0f",
        @"Trigger Event" : @"\u89e6\u53d1\u4e8b\u4ef6",
        @"Trigger Name (Optional)" : @"\u89e6\u53d1\u5668\u540d\u79f0\uff08\u53ef\u9009\uff09",
        @"Triggers" : @"\u89e6\u53d1\u5668",
        @"Unacceptable protocol version" : @"\u4e0d\u53ef\u63a5\u53d7\u7684\u534f\u8bae\u7248\u672c",
        @"Unauthorized (check HA token)" : @"\u672a\u6388\u6743\uff08\u68c0\u67e5 HA \u4ee4\u724c\uff09",
        @"Unknown Action" : @"\u672a\u77e5\u52a8\u4f5c",
        @"Unlock Device" : @"\u89e3\u9501\u8bbe\u5907",
        @"Untitled" : @"\u672a\u547d\u540d",
        @"Update Bluetooth Connection" : @"\u66f4\u65b0\u84dd\u7259\u8fde\u63a5",
        @"Update Bluetooth Disconnect" : @"\u66f4\u65b0\u84dd\u7259\u65ad\u5f00",
        @"Update your Lua code" : @"\u66f4\u65b0\u4f60\u7684 Lua \u4ee3\u7801",
        @"Update your terminal command" : @"\u66f4\u65b0\u4f60\u7684\u7ec8\u7aef\u547d\u4ee4",
        @"Userspace Reboot" : @"\u7528\u6237\u7a7a\u95f4\u91cd\u542f",
        @"Video (0.5x)" : @"\u89c6\u9891\uff080.5x\uff09",
        @"Video (1x)" : @"\u89c6\u9891\uff081x\uff09",
        @"Video (1x, Flash)" : @"\u89c6\u9891\uff081x\uff0c\u95ea\u5149\u706f\uff09",
        @"Video (2x)" : @"\u89c6\u9891\uff082x\uff09",
        @"Video (2x, Flash)" : @"\u89c6\u9891\uff082x\uff0c\u95ea\u5149\u706f\uff09",
        @"Video (Front)" : @"\u89c6\u9891\uff08\u524d\u7f6e\uff09",
        @"Volume Buttons" : @"\u97f3\u91cf\u952e",
        @"Volume Down" : @"\u97f3\u91cf\u51cf",
        @"Volume Down Hold" : @"\u97f3\u91cf\u51cf\u957f\u6309",
        @"Volume Down then Up" : @"\u97f3\u91cf\u51cf\u540e\u97f3\u91cf\u52a0",
        @"Volume Up" : @"\u97f3\u91cf\u52a0",
        @"Volume Up + Down (Both)" : @"\u97f3\u91cf\u52a0 + \u51cf\uff08\u540c\u65f6\uff09",
        @"Volume Up Hold" : @"\u97f3\u91cf\u52a0\u957f\u6309",
        @"Volume Up then Down" : @"\u97f3\u91cf\u52a0\u540e\u97f3\u91cf\u51cf",
        @"Web Server Details" : @"Web \u670d\u52a1\u5668\u8be6\u60c5",
        @"WiFi Network Triggers" : @"WiFi \u7f51\u7edc\u89e6\u53d1\u5668",
        @"WiFi Toggle" : @"WiFi \u5207\u6362",
    } copy];
    NSMutableArray *arr = [NSMutableArray array];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Recording tap in (\\d+)\\.\\.\\.$" options:0 error:nil], @[@"{0} \u79d2\u540e\u5f55\u5236\u70b9\u51fb\u2026"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Connected to MQTT broker \\((.+):(\\d+)\\) successfully!$" options:0 error:nil], @[@"\u5df2\u8fde\u63a5 MQTT \u670d\u52a1\u5668\uff08{0}:{1}\uff09\uff01"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Server returned HTTP status (\\d+)$" options:0 error:nil], @[@"\u670d\u52a1\u5668\u8fd4\u56de HTTP \u72b6\u6001 {0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Loaded (\\d+) action\\(s\\)\\.$" options:0 error:nil], @[@"\u5df2\u52a0\u8f7d {0} \u4e2a\u52a8\u4f5c\u3002"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Wait ([0-9.]+)s$" options:0 error:nil], @[@"\u7b49\u5f85 {0} \u79d2"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Delay ([0-9.]+)s$" options:0 error:nil], @[@"\u5ef6\u8fdf {0} \u79d2"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Toggle \\((.+)\\)$" options:0 error:nil], @[@"\u5207\u6362\uff08{0}\uff09"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Turn On \\((.+)\\)$" options:0 error:nil], @[@"\u6253\u5f00\uff08{0}\uff09"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Turn Off \\((.+)\\)$" options:0 error:nil], @[@"\u5173\u95ed\uff08{0}\uff09"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Parameter: (.+)$" options:0 error:nil], @[@"\u53c2\u6570\uff1a{0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Trigger: (.+)$" options:0 error:nil], @[@"\u89e6\u53d1\u5668\uff1a{0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Any Notification from (.+)$" options:0 error:nil], @[@"\u6765\u81ea {0} \u7684\u4efb\u610f\u901a\u77e5"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Any Notification containing '(.+)'$" options:0 error:nil], @[@"\u5305\u542b\u300c{0}\u300d\u7684\u4efb\u610f\u901a\u77e5"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Notification from (.+) containing '(.+)'$" options:0 error:nil], @[@"\u6765\u81ea {0} \u4e14\u5305\u542b\u300c{1}\u300d\u7684\u901a\u77e5"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Connect (.+)$" options:0 error:nil], @[@"\u8fde\u63a5 {0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Disconnect (.+)$" options:0 error:nil], @[@"\u65ad\u5f00 {0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Kill (.+)$" options:0 error:nil], @[@"\u7ed3\u675f {0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Launch (.+)$" options:0 error:nil], @[@"\u542f\u52a8 {0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Open (.+)$" options:0 error:nil], @[@"\u6253\u5f00 {0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Run (.+)$" options:0 error:nil], @[@"\u8fd0\u884c {0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Swipe (.+)$" options:0 error:nil], @[@"\u6ed1\u52a8 {0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Hold at (.+)$" options:0 error:nil], @[@"\u957f\u6309 {0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Tap at (.+)$" options:0 error:nil], @[@"\u70b9\u51fb {0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Repeat (.+)$" options:0 error:nil], @[@"\u91cd\u590d {0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Set Brightness (.+)$" options:0 error:nil], @[@"\u8bbe\u7f6e\u4eae\u5ea6 {0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Set Volume (.+)$" options:0 error:nil], @[@"\u8bbe\u7f6e\u97f3\u91cf {0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Flashlight ([0-9.]+)%$" options:0 error:nil], @[@"\u624b\u7535\u7b52 {0}%"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^HA Toggle: (.+)$" options:0 error:nil], @[@"HA \u5207\u6362\uff1a{0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^HA Turn On: (.+)$" options:0 error:nil], @[@"HA \u6253\u5f00\uff1a{0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^HA Turn Off: (.+)$" options:0 error:nil], @[@"HA \u5173\u95ed\uff1a{0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^HA Call (.+)$" options:0 error:nil], @[@"HA \u8c03\u7528 {0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^HA: (.+)$" options:0 error:nil], @[@"HA\uff1a{0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^KM: (.+) \\((.+)\\)$" options:0 error:nil], @[@"KM\uff1a{0}\uff08{1}\uff09"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^KM: (.+)$" options:0 error:nil], @[@"KM\uff1a{0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^MQTT: (.+) \\((.+)\\)$" options:0 error:nil], @[@"MQTT\uff1a{0}\uff08{1}\uff09"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^MQTT: (.+)$" options:0 error:nil], @[@"MQTT\uff1a{0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^NFC Tag (.+)$" options:0 error:nil], @[@"NFC \u6807\u7b7e {0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Error \\(NDEF\\): (.+)$" options:0 error:nil], @[@"\u9519\u8bef\uff08NDEF\uff09\uff1a{0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Could not read file: (.+)$" options:0 error:nil], @[@"\u65e0\u6cd5\u8bfb\u53d6\u6587\u4ef6\uff1a{0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Found: (.+)$" options:0 error:nil], @[@"\u627e\u5230\uff1a{0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Open Camera \\((.+)\\)$" options:0 error:nil], @[@"\u6253\u5f00\u76f8\u673a\uff08{0}\uff09"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^(.+) Time is Between (.+)$" options:0 error:nil], @[@"{0} \u65f6\u95f4\u4ecb\u4e8e {1}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^(.+) seconds$" options:0 error:nil], @[@"{0} \u79d2"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^(.+) is\\.\\.\\.$" options:0 error:nil], @[@"{0} \u662f\u2026"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Could not connect to (.+)$" options:0 error:nil], @[@"\u65e0\u6cd5\u8fde\u63a5 {0}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Could not resolve host '(.+)'$" options:0 error:nil], @[@"\u65e0\u6cd5\u89e3\u6790\u4e3b\u673a\u300c{0}\u300d"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^last ([0-9.]+), ([0-9.]+)$" options:0 error:nil], @[@"\u4e0a\u6b21 {0}, {1}"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^Tap Target \\((\\d+)\\)$" options:0 error:nil], @[@"\u70b9\u51fb\u76ee\u6807\uff08{0}\uff09"] ]];
    [arr addObject:@[ [[NSRegularExpression alloc] initWithPattern:@"^RemoteCompanion Tap Test\\nhits (\\d+)\\n(.*)$" options:0 error:nil], @[@"RemoteCompanion \u70b9\u51fb\u6d4b\u8bd5\n\u547d\u4e2d {0}\n{1}"] ]];
    RCCNRegex = [arr copy];
    NSMutableDictionary *low = [NSMutableDictionary dictionaryWithCapacity:RCCNExact.count];
    for (NSString *k in RCCNExact) low[[k lowercaseString]] = RCCNExact[k];
    RCCNLower = [low copy];
}


%hook UILabel
- (void)setText:(NSString *)text {
    NSString *t = RCCNTranslate(text); %orig(t);
}
- (void)setAttributedText:(NSAttributedString *)text {
    if (!text) { %orig; return; }
    NSString *t = RCCNTranslate(text.string);
    if ([t isEqualToString:text.string]) { %orig; return; }
    NSMutableAttributedString *m = [text mutableCopy];
    [m replaceCharactersInRange:NSMakeRange(0, m.length) withString:t];
    %orig(m);
}
%end

%hook UIListContentConfiguration
- (void)setText:(NSString *)text {
    NSString *t = RCCNTranslate(text); %orig(t);
}
- (void)setSecondaryText:(NSString *)text {
    NSString *t = RCCNTranslate(text); %orig(t);
}
%end

%hook UITextField
- (void)setText:(NSString *)text {
    NSString *t = RCCNTranslate(text); %orig(t);
}
%end

%hook UITextField
- (void)setPlaceholder:(NSString *)p {
    NSString *t = RCCNTranslate(p); %orig(t);
}
%end

%hook UIButton
- (void)setTitle:(NSString *)title forState:(UIControlState)state {
    NSString *t = RCCNTranslate(title); %orig(t, state);
}
%end

%hook UIBarButtonItem
- (instancetype)initWithTitle:(NSString *)title style:(UIBarButtonItemStyle)style target:(id)target action:(SEL)action {
    NSString *t = RCCNTranslate(title); return %orig(t, style, target, action);
}
- (void)setTitle:(NSString *)title {
    NSString *t = RCCNTranslate(title); %orig(t);
}
%end

%hook UIAlertController
- (instancetype)initWithTitle:(NSString *)title message:(NSString *)message preferredStyle:(UIAlertControllerStyle)style {
    NSString *t = RCCNTranslate(title); NSString *m = RCCNTranslate(message); return %orig(t, m, style);
}
- (void)setTitle:(NSString *)title {
    NSString *t = RCCNTranslate(title); %orig(t);
}
- (void)setMessage:(NSString *)message {
    NSString *t = RCCNTranslate(message); %orig(t);
}
%end

%hook UIAlertAction
- (instancetype)initWithTitle:(NSString *)title style:(UIAlertActionStyle)style handler:(void (^)(UIAlertAction *))handler {
    NSString *t = RCCNTranslate(title); return %orig(t, style, handler);
}
- (void)setTitle:(NSString *)title {
    NSString *t = RCCNTranslate(title); %orig(t);
}
%end



%hook UIMenu
- (instancetype)initWithTitle:(NSString *)title image:(UIImage *)image identifier:(UIMenuIdentifier)identifier options:(UIMenuOptions)options children:(NSArray<UIMenuElement *> *)children {
    NSString *t = RCCNTranslate(title); return %orig(t, image, identifier, options, children);
}
%end

%hook UITableViewHeaderFooterView
- (void)setTextLabel:(UILabel *)label {
    UILabel *l = label;
    l.text = RCCNTranslate(l.text);
    %orig(l);
}
%end


%ctor {
    RCCNInit();
}
