# -*- coding: utf-8 -*-
# rc_webui.html 汉化：只替换整串匹配（'X' 带引号、>X<、属性值），不动命令/类名/SF Symbol
import re

M = {
"API Calls": "API 调用",
"Action executed successfully": "动作执行成功",
"Activate Siri": "激活 Siri",
"Add": "添加",
"Add Delay": "添加延迟",
"Add HUD Toast": "添加 HUD 弹窗",
"Add New Trigger": "新建触发器",
"AirPlay Receiver name:": "AirPlay 接收器名称：",
"Airplane Mode": "飞行模式",
"All Logs": "全部日志",
"Any Notification": "任意通知",
"App Launch Trigger": "应用启动触发器",
"App Launch Triggers": "应用启动触发器",
"App Switcher": "多任务切换器",
"Appearance": "外观",
"Appearance Dark": "外观：深色",
"Appearance Light": "外观：浅色",
"Appearance Toggle": "外观：切换",
"Are you sure you want to respring your iOS device?": "确定要注销（Respring）iOS 设备吗？",
"Auto-scroll to bottom": "自动滚动到底部",
"Backup": "备份",
"Battery Level": "电池电量",
"Block": "屏蔽",
"Bottom Bar Gestures": "底部横条手势",
"Bottom Bar Swipe Left": "底部横条左滑",
"Bottom Bar Swipe Right": "底部横条右滑",
"Bottom Swipe Up (Center)": "底部上滑（中部）",
"Bottom Swipe Up (Left)": "底部上滑（左）",
"Bottom Swipe Up (Right)": "底部上滑（右）",
"Brightness": "亮度",
"Brightness % (0-100):": "亮度 %（0-100）：",
"Brightness percentage (0-100):": "亮度百分比（0-100）：",
"Brightness percentage (1-100):": "亮度百分比（1-100）：",
"Bundle ID:": "Bundle ID：",
"Camera Record Toggle": "相机录制开关",
"Cancel": "取消",
"Category:": "分类：",
"Cellular Data": "蜂窝数据",
"Change Macro…": "更改宏…",
"Cinematic": "电影模式",
"Clear Actions": "清除动作",
"Clear All Actions": "清除全部动作",
"Clear Log File": "清空日志文件",
"Clear Log File?": "清空日志文件？",
"Condition": "条件",
"Configure HUD toast alert displayed on device:": "配置设备上显示的 HUD 弹窗：",
"Connect": "连接",
"Connect AirPlay": "连接 AirPlay",
"Connect AirPlay…": "连接 AirPlay…",
"Connect Bluetooth": "连接蓝牙",
"Connect Bluetooth…": "连接蓝牙…",
"Connection failed": "连接失败",
"Connectivity": "连接",
"Control Center": "控制中心",
"Copied": "已复制",
"Copy": "复制",
"Copy API Link": "复制 API 链接",
"Copy Action": "复制动作",
"Copy failed:": "复制失败：",
"Could not fetch macros": "无法获取宏",
"Create": "创建",
"Dark": "深色",
"Delay duration in seconds:": "延迟时长（秒）：",
"Delay…": "延迟…",
"Delete": "删除",
"Delete Action": "删除动作",
"Delete Currently Playing Song": "删除当前播放歌曲",
"Delete Trigger": "删除触发器",
"Device Controls": "设备控制",
"Device Locked": "设备已锁定",
"Device Status": "设备状态",
"Device Unlocked": "设备已解锁",
"Device name or MAC address:": "设备名称或 MAC 地址：",
"Device Name or MAC Address:": "设备名称或 MAC 地址：",
"Diagnostics": "诊断",
"Disable Action": "停用动作",
"Disconnect": "断开",
"Disconnect AirPlay": "断开 AirPlay",
"Disconnect Bluetooth": "断开蓝牙",
"Disconnect Bluetooth…": "断开蓝牙…",
"Disk Space": "磁盘空间",
"Do Not Disturb": "专注模式",
"Do Not Disturb Off": "专注模式：关",
"Do Not Disturb On": "专注模式：开",
"Do Not Disturb Toggle": "专注模式：切换",
"Done": "完成",
"Edit": "编辑",
"Edit Action": "编辑动作",
"Edit App Trigger": "编辑应用触发器",
"Edit Bluetooth Trigger": "编辑蓝牙触发器",
"Edit Brightness Level": "编辑亮度数值",
"Edit Delay": "编辑延迟",
"Edit Flashlight Level": "编辑手电筒亮度",
"Edit Kill App": "编辑结束应用",
"Edit Notification Trigger": "编辑通知触发器",
"Edit Open App": "编辑打开应用",
"Edit Repeat Count": "编辑重复次数",
"Edit Scheduled Trigger": "编辑定时触发器",
"Edit Shortcut": "编辑快捷指令",
"Edit Terminal Command": "编辑终端命令",
"Edit Toast Notification": "编辑弹窗通知",
"Edit Volume Level": "编辑音量数值",
"Edit WiFi Trigger": "编辑 WiFi 触发器",
"Else": "否则",
"Enable Action": "启用动作",
"Enable All Triggers": "启用全部触发器",
"Enabled": "已启用",
"End If": "结束如果",
"End Time": "结束时间",
"Enter Macro Name or UUID (and optional value):": "输入宏名称或 UUID（可附带值）：",
"Enter Safe Mode?": "进入安全模式？",
"Enter shell command to execute on device:": "输入要在设备上执行的 shell 命令：",
"Enter value:": "输入值：",
"Entering Safe Mode…": "正在进入安全模式…",
"Exact name of the iOS Shortcut:": "iOS 快捷指令的确切名称：",
"Exact payload to match, or leave empty for Any:": "要匹配的确切内容，留空为任意：",
"Export Actions": "导出动作",
"Export Configuration": "导出配置",
"Favorite": "收藏",
"Favorites": "收藏夹",
"Fetching system logs…": "正在获取系统日志…",
"Flash": "闪光灯",
"Flashlight": "手电筒",
"Flashlight Intensity": "手电筒亮度",
"Flashlight Intensity…": "手电筒亮度…",
"Flashlight Off": "手电筒：关",
"Flashlight On": "手电筒：开",
"Flashlight Toggle": "手电筒：切换",
"Flush DNS": "刷新 DNS",
"Free:": "可用：",
"Front": "前置",
"Front App is": "前台应用为",
"Front Selfie": "前置自拍",
"General": "通用",
"Haptic Feedback": "触感反馈",
"Hardware Resources": "硬件资源",
"Home (Double Click)": "Home 键（双击）",
"Home (Quadruple Click)": "Home 键（四连击）",
"Home (Triple Click)": "Home 键（三连击）",
"Home Assistant": "Home Assistant",
"Home Assistant Action": "Home Assistant 动作",
"Home Assistant Control": "Home Assistant 控制",
"Home Assistant not connected": "Home Assistant 未连接",
"Home Assistant: Control Entity…": "Home Assistant：控制实体…",
"Home Button": "Home 键",
"Hostname": "主机名",
"Hot": "过热",
"If Condition…": "如果条件…",
"Import": "导入",
"Import Actions": "导入动作",
"Import Configuration": "导入配置",
"Intensity % (1-100):": "亮度 %（1-100）：",
"Jailbroken": "已越狱",
"Keyboard Maestro": "Keyboard Maestro",
"Keyboard Maestro Action": "Keyboard Maestro 动作",
"Keyboard Maestro Macros": "Keyboard Maestro 宏",
"Keyboard Maestro: Trigger Macro…": "Keyboard Maestro：触发宏…",
"Kill App…": "结束应用…",
"Landscape": "横屏",
"Left Edge Swipe Down": "左缘下滑",
"Left Edge Swipe Up": "左缘上滑",
"Light": "浅色",
"Loading Home Assistant entities…": "正在加载 Home Assistant 实体…",
"Loading apps…": "正在加载应用…",
"Loading macros from Mac…": "正在从 Mac 加载宏…",
"Local IP": "本地 IP",
"Location Services": "定位服务",
"Location Services Off": "定位服务：关",
"Location Services On": "定位服务：开",
"Location Services Toggle": "定位服务：切换",
"Lock": "锁定",
"Lock Device": "锁定设备",
"Lock Status": "锁定状态",
"Locked": "已锁定",
"Log Buffer Size": "日志缓冲区大小",
"Logs cleared from view": "已清空视图日志",
"Low Power Mode": "低电量模式",
"Low Power Off": "低电量：关",
"Low Power On": "低电量：开",
"Low Power Toggle": "低电量：切换",
"Lua Script": "Lua 脚本",
"Lua Script…": "Lua 脚本…",
"Lua expression or script:": "Lua 表达式或脚本：",
"MQTT Payload": "MQTT 内容",
"MQTT Subscription Triggers": "MQTT 订阅触发器",
"MQTT Topic Trigger": "MQTT 主题触发器",
"MQTT: Publish": "MQTT：发布",
"MQTT: Publish Topic": "MQTT：发布主题",
"MQTT: Publish Topic…": "MQTT：发布主题…",
"Manual Entry…": "手动输入…",
"Media Paused": "媒体已暂停",
"Media Playing": "媒体播放中",
"Media Track Changed": "媒体曲目切换",
"Message text:": "消息文本：",
"Motion Gestures": "动作手势",
"Mute": "静音",
"Mute Off": "静音：关",
"Mute On": "静音：开",
"Mute Toggle": "静音：切换",
"Next Track": "下一曲",
"No log entries recorded": "暂无日志记录",
"No logs to copy": "无可复制日志",
"No matching log lines found": "未找到匹配的日志行",
"No matching logs to copy": "无匹配日志可复制",
"Not configured": "未配置",
"Notification Trigger": "通知触发器",
"Notification Triggers": "通知触发器",
"Off": "关",
"On": "开",
"Open App…": "打开应用…",
"Open Camera": "打开相机",
"Open Settings": "打开设置",
"Open Video Camera": "打开视频相机",
"Open Video Camera…": "打开视频相机…",
"Orientation": "方向",
"Pause": "暂停",
"Paused": "已暂停",
"Payload Match (Optional)": "内容匹配（可选）",
"Photo": "照片",
"Play": "播放",
"Player": "播放器",
"Playing": "播放中",
"Portrait": "竖屏",
"Power Button": "电源键",
"Power Connected": "已接通电源",
"Power Disconnected": "电源已断开",
"Power Double-Tap": "电源键双击",
"Power Long Press": "电源键长按",
"Power Quadruple Click": "电源键四连击",
"Power Triple Click": "电源键三连击",
"Previous App": "上一个应用",
"Previous Track": "上一曲",
"Queue Artist (Shuffle)": "排队艺人（随机）",
"Queue Current Album": "排队当前专辑",
"Quick Maintenance": "快速维护",
"RAM Memory": "内存",
"Raw Entry:": "原始条目：",
"Record": "录制",
"Refresh Icon Cache": "刷新图标缓存",
"RemoteCompanion": "RemoteCompanion",
"Remove Parameter": "移除参数",
"Repeat": "重复",
"Respring": "注销",
"Respringing SpringBoard…": "正在注销 SpringBoard…",
"Restart SpringBoard interface": "重启 SpringBoard 界面",
"Restart SpringBoard with tweaks disabled": "以禁用插件方式重启 SpringBoard",
"Restart SpringBoard?": "重启 SpringBoard？",
"Retry": "重试",
"Right Edge Swipe Down": "右缘下滑",
"Right Edge Swipe Up": "右缘上滑",
"Ring Vibration": "响铃振动",
"Ringer Muted": "铃声已静音",
"Ringer Switch": "响铃开关",
"Ringer Toggled": "响铃已切换",
"Ringer Unmuted": "铃声已取消静音",
"Root Privileges": "Root 权限",
"Rotate Lock": "旋转锁定",
"Rotate Toggle": "旋转切换",
"Rotate Unlock": "旋转解锁",
"Rotation Lock": "竖排方向锁定",
"Run Action Now": "立即运行动作",
"Run Shortcut": "运行快捷指令",
"Run Trigger": "运行触发器",
"Run actions only between these times:": "仅在这些时间段内运行动作：",
"Scheduled": "定时",
"Scheduled Trigger": "定时触发器",
"Scheduled Triggers": "定时触发器",
"Screen Gestures": "屏幕手势",
"Screen Recording": "屏幕录制",
"Screen Recording Status": "屏幕录制状态",
"Screen Recording Toggle": "屏幕录制切换",
"Screen Resolution": "屏幕分辨率",
"Screenshot": "截屏",
"Seconds:": "秒数：",
"Select Action": "选择动作",
"Select Condition Target": "选择条件目标",
"Select Device": "选择设备",
"Select a macro from your Mac to execute:": "从 Mac 选择要执行的宏：",
"Set Brightness": "设置亮度",
"Set Brightness…": "设置亮度…",
"Set Volume": "设置音量",
"Set Volume…": "设置音量…",
"Settings": "设置",
"Shake Device": "摇动设备",
"Shell command to execute:": "要执行的 shell 命令：",
"Shortcuts: Run Shortcut…": "快捷指令：运行快捷指令…",
"Shuffle All Songs": "随机播放全部歌曲",
"Silent Vibration": "静音振动",
"Snap": "快照",
"Soft Reboot": "软重启",
"Start Screen Recording": "开始屏幕录制",
"Start Time": "开始时间",
"Status Bar Center Hold": "状态栏中部长按",
"Status Bar Double Tap": "状态栏双击",
"Status Bar Left Hold": "状态栏左侧长按",
"Status Bar Right Hold": "状态栏右侧长按",
"Status Bar Swipe Left": "状态栏左滑",
"Status Bar Swipe Right": "状态栏右滑",
"Stop Screen Recording": "停止屏幕录制",
"Stopped": "已停止",
"Storage": "存储",
"Subtitle": "副标题",
"Swipe Down": "下滑",
"Swipe Left": "左滑",
"Swipe Right": "右滑",
"Swipe Up": "上滑",
"System Memory": "系统内存",
"System Uptime": "系统运行时长",
"Tap tag against phone, or enter Tag ID:": "将标签贴近手机，或输入标签 ID：",
"Terminal Action": "终端动作",
"Terminal Command": "终端命令",
"Terminal Command…": "终端命令…",
"Test Macro": "测试宏",
"Thermal State": "温度状态",
"Time Range": "时间范围",
"Time of Day (Between)": "时段（介于）",
"Time of Day Condition": "时段条件",
"Times to loop:": "循环次数：",
"Timestamp:": "时间戳：",
"Toast Notification": "弹窗通知",
"Toast Title": "弹窗标题",
"Toggle": "切换",
"Toggle Home Assistant Entity": "切换 Home Assistant 实体",
"Total Logs": "日志总数",
"Touch ID Hold (Rest Finger)": "Touch ID 长按（轻触不放）",
"Touch ID Tap": "Touch ID 点按",
"Transparency Mode": "通透模式",
"Trigger (No Parameter)": "触发（无参数）",
"Trigger Configuration": "触发器配置",
"Trigger with Parameter…": "带参数触发…",
"Turn Off Home Assistant Entity": "关闭 Home Assistant 实体",
"Turn On Home Assistant Entity": "打开 Home Assistant 实体",
"Tweak Log Storage": "插件日志存储",
"UICache refresh triggered": "已触发图标缓存刷新",
"Unavailable": "不可用",
"Unfavorite": "取消收藏",
"Unknown": "未知",
"Unlock": "解锁",
"Unlock Device": "解锁设备",
"Unlocked": "已解锁",
"Unplugged": "未接电源",
"Userspace Reboot": "用户空间重启",
"Value": "值",
"Video": "视频",
"Volume % (0-100):": "音量 %（0-100）：",
"Volume Buttons": "音量键",
"Volume Down": "音量减",
"Volume Down Hold": "音量减长按",
"Volume Down then Up": "音量减后加",
"Volume Up": "音量加",
"Volume Up + Down (Both)": "音量加+减（同按）",
"Volume Up Hold": "音量加长按",
"Volume Up then Down": "音量加后减",
"Volume percentage (0-100):": "音量百分比（0-100）：",
"Warm": "偏热",
"Web UI": "网页控制台",
"Web UI URL copied to clipboard": "网页控制台 URL 已复制",
"WiFi Network Trigger": "WiFi 网络触发器",
"WiFi Network Triggers": "WiFi 网络触发器",
"Location Services": "定位服务",
"Toggle": "切换",
# 提示/状态
"⚠ Cannot save while offline": "⚠ 离线状态无法保存",
"⚠ Connection error": "⚠ 连接错误",
"⚠ Copy Failed": "⚠ 复制失败",
"⚠ Could not connect to device": "⚠ 无法连接设备",
"⚠ Enable Web UI in Settings first": "⚠ 请先在设置中启用网页控制台",
"⚠ Failed to refresh macros": "⚠ 刷新宏失败",
"⚠ Failed to save settings": "⚠ 保存设置失败",
"⚠ Home Assistant connection failed": "⚠ Home Assistant 连接失败",
"⚠ Invalid Backup File": "⚠ 无效的备份文件",
"⚠ Keyboard Maestro connection failed": "⚠ Keyboard Maestro 连接失败",
"⚠ MQTT connection failed": "⚠ MQTT 连接失败",
"⚠ Missing Broker Host": "⚠ 缺少服务器主机",
"⚠ Missing URL or Token": "⚠ 缺少 URL 或令牌",
"⚠ Missing Web Server URL": "⚠ 缺少 Web 服务器 URL",
"⚠ No valid actions found": "⚠ 未找到有效动作",
"⚠ Offline - unable to save": "⚠ 离线 - 无法保存",
"⚠ Record Failed": "⚠ 录制失败",
"⚠ Server Error": "⚠ 服务器错误",
"⚠ Server request error": "⚠ 服务器请求错误",
"✓ Action Copied": "✓ 动作已复制",
"✓ Action Pasted": "✓ 动作已粘贴",
"✓ Actions Copied": "✓ 动作已复制",
"✓ Configuration Imported": "✓ 配置已导入",
"✓ Connected!": "✓ 已连接！",
"✓ Home Assistant connection successful": "✓ Home Assistant 连接成功",
"✓ Keyboard Maestro connection successful": "✓ Keyboard Maestro 连接成功",
"✓ MQTT connection successful": "✓ MQTT 连接成功",
"✓ NFC Tag Recorded": "✓ NFC 标签已记录",
"✓ Refreshed macros from Mac": "✓ 已从 Mac 刷新宏",
"✓ URL Copied": "✓ URL 已复制",
"📡 Tap NFC tag against phone now…": "📡 现在将 NFC 标签贴近手机…",
"🧹 Tweak log file cleared": "🧹 插件日志文件已清空",
"⏸ Live log streaming paused": "⏸ 实时日志流已暂停",
"▶ Action Sent": "▶ 动作已发送",
"▶ Live log streaming resumed": "▶ 实时日志流已恢复",
"▶ Triggered": "▶ 已触发",
"Choose an action to add to this trigger.": "选择要添加到此触发器的动作。",
"Check KM Web Server status and credentials.": "检查 KM Web 服务器状态和凭据。",
"Delete disk log buffer": "删除磁盘日志缓冲区",
"Failed to clear log file": "清空日志文件失败",
"Failed to copy logs": "复制日志失败",
"Failed to execute action": "执行动作失败",
"Failed to fetch system diagnostics": "获取系统诊断失败",
"Failed to refresh macros": "刷新宏失败",
"Fires when a notification arrives matching these criteria.": "当收到符合这些条件的通知时触发。",
"Fires when an app is opened on the device.": "当设备上打开应用时触发。",
"Paste JSON array or line-separated action commands:": "粘贴 JSON 数组或按行分隔的动作命令：",
"Rebuild system icon cache": "重建系统图标缓存",
"Reset mDNSResponder cache": "重置 mDNSResponder 缓存",
"Enable and configure your Mac's Web Server in Settings.": "请在设置中启用并配置 Mac 的 Web 服务器。",
# 属性占位
"Add Action": "添加动作",
"Add Trigger": "添加触发器",
"App Bundle ID (Blank = All Apps)": "应用 Bundle ID（留空 = 全部应用）",
"Clear": "清除",
"Clear Console View": "清空视图日志",
"Copy Logs to Clipboard": "复制日志到剪贴板",
"Edit Settings": "编辑设置",
"Live Auto-Streaming": "实时自动流式传输",
"Live System Logs": "实时系统日志",
"More Options": "更多选项",
"Name (e.g. Morning)": "名称（如 Morning）",
"Name or SSID": "名称或 SSID",
"Notification Bundle ID Override (optional)": "通知 Bundle ID 覆盖（可选）",
"Optional": "可选",
"Pause/Resume Streaming": "暂停/恢复传输",
"Refresh Diagnostics": "刷新诊断",
"Refresh Macros": "刷新宏",
"Refresh Now": "立即刷新",
"Run": "运行",
"SF Symbol Icon (optional, e.g. bell.fill)": "SF Symbol 图标（可选，如 bell.fill）",
"Search actions…": "搜索动作…",
"Search apps…": "搜索应用…",
"Search entities (light, switch, scene...)": "搜索实体（light、switch、scene…）",
"Search log entries...": "搜索日志条目…",
"Search macros and groups…": "搜索宏与分组…",
"192.168.1.50 or broker.local": "如 192.168.1.50 或 broker.local",
"Battery & Power": "电池与电源",
"Display & System": "显示与系统",
"Scripting & Logic": "脚本与逻辑",
"Screen Recording Toggle": "屏幕录制切换",
"Enable All Triggers": "启用全部触发器",
"Import Configuration": "导入配置",
"Export Configuration": "导出配置",
"Import Actions": "导入动作",
"Log Buffer Size": "日志缓冲区大小",
"Device Locked": "设备已锁定",
"Device Unlocked": "设备已解锁",
"Media Paused": "媒体已暂停",
"Media Playing": "媒体播放中",
"Media Track Changed": "媒体曲目切换",
"Power Connected": "已接通电源",
"Power Disconnected": "电源已断开",
"NFC Scanning": "NFC 扫描中",
}

# 模板标题
M["<title>RemoteCompanion</title>"] = "<title>RemoteCompanion 中文版</title>"

src = open('rc_webui.html', encoding='utf-8').read()

# 1) 整串带引号替换（JS 字符串）：'X' → '译'
# 2) >X< 标签间文本
# 3) 属性值 ="X"
pairs = sorted(M.items(), key=lambda kv: -len(kv[0]))
n1 = n2 = n3 = 0
for en, cn in pairs:
    if en.startswith("<title>"): continue
    q = "'" + en + "'"
    c = q in src
    if c:
        src = src.replace(q, "'" + cn + "'"); n1 += 1
    d = '"' + en + '"'
    if d in src:
        src = src.replace(d, '"' + cn + '"'); n2 += 1
    t = ">" + en + "<"
    if t in src:
        src = src.replace(t, ">" + cn + "<"); n3 += 1

src = src.replace("<title>RemoteCompanion</title>", "<title>RemoteCompanion 中文版</title>")
open('rc_webui.html.cn', 'w', encoding='utf-8').write(src)
print("quoted-single:", n1, "quoted-double:", n2, "tag-text:", n3)
